#!/usr/bin/env python3

import Levenshtein
import sys

cmd = sys.argv[1]
file_path = sys.argv[2]
with open(file_path) as f:
  list = f.read().split("\n")

min_distance = 100
nearest = None
for _cmd in list:
  distance = Levenshtein.distance(cmd, _cmd)
  if min_distance > distance:
    min_distance = distance
    nearest = _cmd

if min_distance < 3:
    print(nearest)

